language: node_js
node_js:
    - "0.10"
before_install:
    - "npm install -g bower"
    - "npm install -g grunt-cli"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
#   Meteor Tinytest support
    - "npm install -g spacejam"
install:
    - "npm install"
    - "bower install"

script: 
    - "npm test"
    - "spacejam test-packages nvd3:nvd3"

